import { expect, test } from '@playwright/test'

test('striker role ability drilldown, comparison and keyboard navigation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.locator('.ss-summary')).toHaveAttribute('aria-busy', 'false')
  await page.getByRole('button', { name: /^Select Alexander Isak,/ }).click()
  await page.getByRole('button', { name: 'Details', exact: true }).click()
  await expect(page.getByLabel('Evaluation role')).toBeVisible()
  await expect(page.locator('.av-axis')).toHaveCount(6)
  await expect(page.locator('.av-feature')).toHaveCount(8)
  await expect(page.locator('.av-gap')).toHaveCount(8)
  await page.getByRole('button', { name: /^Physicality, rating/ }).click()
  await expect(page.locator('.av-ability-details h3')).toHaveText('Physicality')
  await expect(page.locator('.av-feature')).toHaveCount(6)
  await page.getByLabel('Evaluation role').selectOption('false-nine')
  await expect(page.locator('.av-role-summary')).toContainText('False Nine')
  await page.getByLabel('Compare one striker').selectOption('lfc-hugo-ekitike')
  await expect(page.locator('.av-comparison-polygon')).toBeVisible()
  await page.getByRole('button', {name:'Inspect Duels won evidence',exact:true}).click()
  await expect(page.locator('.av-evidence-panel')).toContainText('Comparison raw value')
  await page.getByLabel('Scan Duels won distribution').press('ArrowRight')
  await expect(page.locator('.av-evidence-panel [aria-live]')).toContainText('approximate raw percentile')
  await page.getByRole('button', { name: /^Physicality, rating/ }).press('ArrowRight')
  await expect(page.locator('.av-ability-details h3')).toHaveText('Defensive Activity')
  await expect(page.locator('.av-feature')).toHaveCount(4)
  await page.getByRole('button', { name: /^Defensive Activity, rating/ }).press('Enter')
  await expect(page.locator('.av-axis[aria-pressed=true]')).toHaveAttribute('aria-label', /Defensive Activity/)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await page.locator('.av-ability-details').evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('unrated role and incompatible comparison retain unavailable evidence', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.route('**/players/*/abilities', async route => {
    const response = await route.fetch()
    const body = await response.json()
    if (body.player_id === 'lfc-alexander-isak') {
      const role = body.roles.find((r: {role_id: string}) => r.role_id === 'false-nine')
      Object.assign(role, {rating: null, rating_unclipped: null, role_z: null, percentile: null, population_size: 0, rank: null})
      for (const ability of role.abilities) {
        Object.assign(ability, {raw: null, z: null, rating: null, rating_unclipped: null, percentile: null})
        for (const feature of ability.features) Object.assign(feature, {peer_count: 0, peer_mean: null, z: null, percentile: null, stabilized_value: null, reliability: null, density: [], quantiles: []})
      }
    } else body.competition = 'Different test cohort'
    await route.fulfill({response, json: body})
  })
  await page.goto('/')
  await expect(page.locator('.ss-summary')).toHaveAttribute('aria-busy', 'false')
  await page.getByRole('button', {name: /^Select Alexander Isak,/}).click()
  await page.getByRole('button', {name: 'Details', exact: true}).click()
  await page.getByLabel('Evaluation role').selectOption('false-nine')
  await expect(page.getByText('Insufficient evidence for a complete ability polygon.', {exact: false})).toBeVisible()
  await expect(page.locator('.av-player-polygon')).toHaveCount(0)
  await expect(page.locator('.av-axis circle')).toHaveCount(0)
  await expect(page.locator('.av-density')).toHaveCount(0)
  await expect(page.locator('.av-axis-number').first()).toHaveText('—')
  await page.getByRole('button', {name: 'Inspect Non-penalty goals evidence', exact: true}).click()
  await expect(page.getByLabel('Scan Non-penalty goals distribution')).toBeDisabled()
  await page.getByLabel('Compare one striker').selectOption('lfc-hugo-ekitike')
  await expect(page.getByText('Comparison unavailable: these players use different evidence', {exact: false})).toBeVisible()
  await expect(page.locator('.av-comparison-polygon')).toHaveCount(0)
  await expect(page.locator('.av-comparison-readout')).toHaveCount(0)
  await page.getByLabel('Evaluation role').selectOption('ST')
  await expect(page.locator('.av-player-polygon')).toBeVisible()
  expect(errors).toEqual([])
})
