import { expect, test } from '@playwright/test'

test('recruit, inspect, compare, save, simulate and export evidence', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/scout')
  await expect(page.getByText('Synthetic demonstration.', { exact: true })).toBeVisible()
  const names = page.locator('.player-name')
  await expect(names.first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await names.first().click({ noWaitAfter: true, timeout: 15000 })
  await page.getByLabel('Scouting notes').fill('Verify pressure receiving in a match.')
  await page.getByLabel('Close evidence').click()
  await page.locator('.candidate-table input[type=checkbox]').first().check()
  await page.locator('.candidate-table input[type=checkbox]').nth(1).check()
  await page.locator('.candidate-table button[aria-label^="Save"]').first().click()
  await page.getByRole('tab', { name: /^Compare/ }).click()
  await expect(page.locator('.comparison-table thead th')).toHaveCount(3)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export comparison' }).click()
  expect((await download).suggestedFilename()).toBe('scout-comparison.json')
  await page.getByRole('tab', { name: 'Squad scenarios' }).click()
  await page.getByText('Squad assignments and fees', { exact: true }).click()
  await page.getByRole('button', { name: 'Assume existing squad fees are €0' }).click()
  const recruitName = await page.getByLabel('Recruit', { exact: true }).locator('option:checked').textContent()
  await page.getByLabel(`${recruitName} fee (€)`, { exact: true }).fill('1000000')
  await page.getByLabel('Scenario budget (€)', { exact: true }).fill('2000000')
  await page.getByText('Squad assignments and fees', { exact: true }).click()
  await page.getByRole('button', { name: 'Run scenario' }).click()
  await expect(page.getByRole('heading', { name: 'Contribution ranges' })).toBeVisible()
  await expect(page.getByText('Entered fees total €1,000,000. Budget: within entered budget.', { exact: false })).toBeVisible()
  await page.getByRole('tab', { name: 'Recruitment', exact: true }).click()
  await page.getByLabel('Max age', { exact: true }).fill('27')
  await expect(page.getByText('Brief changed.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Find candidates' }).click()
  await expect(page.getByText('Brief changed.', { exact: false })).toHaveCount(0)
  await page.reload()
  await expect(names.first()).toBeVisible()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('scout.saved.v1') || '{}'))
  expect(saved.watchlist).toHaveLength(1)
  expect(Object.values(saved.notes)).toContain('Verify pressure receiving in a match.')
  await page.getByRole('tab', { name: 'Data & methods' }).click()
  await expect(page.getByRole('heading', { name: 'Real-data release gate' })).toBeVisible()
  expect(errors).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('data.png'), fullPage: true })
})

test('unavailable API preserves a retry action', async ({ page }) => {
  await page.route('**/api/datasets', route => route.fulfill({ status: 503,
    contentType: 'application/json', body: JSON.stringify({ detail: 'Validated data is unavailable' }) }))
  await page.goto('/scout')
  await expect(page.getByRole('button', { name: 'Retry connection' })).toBeVisible()
})

test('corrupt browser notes are preserved until an explicit recovery', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('scout.saved.v1', '{broken backup'))
  await page.goto('/scout')
  await expect(page.getByText('Stored notes could not be read.', { exact: false })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('scout.saved.v1'))).toBe('{broken backup')
  await page.getByRole('tab', { name: 'Data & methods' }).click()
  await page.getByRole('button', { name: 'Clear local notes' }).click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('scout.saved.v1')))
    .toBe(JSON.stringify({ watchlist: [], notes: {} }))
})
